services:
  - type: web
    name: Kenya-Constitution-AI-Agent
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app/streamlit_app.py --server.port=$PORT --server.address=0.0.0.0"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
